name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version-file: .ruby-version
        bundler-cache: true

    - name: Install vim with server capabilities
      run: |
        sudo apt-get update
        sudo apt-get install -y vim-gtk3 xvfb

    - name: Run tests
      run: xvfb-run -a make test